[package]
name = "kbdc"
version = "0.1.0"
edition = "2024"

[dependencies]
saphyr = "0.0.3"

[dependencies.windows-sys]
version = "0.59"
features = [
    "Win32_System_LibraryLoader",
    "Win32_UI_Input_KeyboardAndMouse"
]